---
- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml

- name: OS is supported
  assert:
    that: yum_os_supported == True

- name: Configuration
  template:
    src: yum.conf.j2
    dest: "{{ yum_config_file }}"
    owner: "{{ yum_config_owner }}"
    group: "{{ yum_config_group }}"
    mode: "{{ yum_config_mode }}"

- name: Register that this role has run
  set_fact: sshd_has_run=true
  when: sshd_has_run is not defined

